name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # A projektünk letöltése egy git checkout segítségével a frissen létrehozott virtuális gépre
    - uses: actions/checkout@v3
    #.NET környezet létrehozása a frissen létrehozott virtuális gépen
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    # Az esetleges .NET-es függőségek kezelése
    - name: Restore dependencies
      run: dotnet restore
    # A projekt lefordítása
    - name: Build
      run: dotnet build --configuration Release --no-restore
    # A tesztek lefuttatása (nincs teszt, így nem csinál semmit)
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Create Release
      uses: ncipollo/release-action@v1.10.0
      with:
        tag: "1.2"
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "./UltimateApp/bin/Release/netcoreapp3.1/UltimateApp" 
      
      


